### ISSUE TITLE
This error occurs when every player enters the server.

### ISSUE THREAD

**Issue by YouaJing** [HSGamer/Topper#80]
[12:37:16 WARN]: [Topper] Async task for Topper v2.5.0 generated an exception
java.lang.UnsupportedOperationException: null
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftScheduler.handle(CraftScheduler.java:533) ~[kaiiju-1.20.1.jar:git-Kaiiju-"4d0e6c8"]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftScheduler.runTaskTimer(CraftScheduler.java:233) ~[kaiiju-1.20.1.jar:git-Kaiiju-"4d0e6c8"]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftScheduler.runTaskTimer(CraftScheduler.java:209) ~[kaiiju-1.20.1.jar:git-Kaiiju-"4d0e6c8"]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftScheduler.runTaskLater(CraftScheduler.java:173) ~[kaiiju-1.20.1.jar:git-Kaiiju-"4d0e6c8"]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftScheduler.runTask(CraftScheduler.java:142) ~[kaiiju-1.20.1.jar:git-Kaiiju-"4d0e6c8"]
        at org.bukkit.scheduler.BukkitRunnable.runTask(BukkitRunnable.java:45) ~[kaiiju-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at me.hsgamer.topper.placeholderleaderboard.core.storage.YamlStorageSupplier$1.save(YamlStorageSupplier.java:64) ~[topper-spigot-placeholder-leaderboard-2.5.0-shaded.jar:?]
        at me.hsgamer.topper.placeholderleaderboard.core.agent.storage.StorageAgent.save(StorageAgent.java:41) ~[topper-spigot-placeholder-leaderboard-2.5.0-shaded.jar:?]
        at me.hsgamer.topper.placeholderleaderboard.core.agent.storage.StorageAgent.lambda$getRunnable$8(StorageAgent.java:104) ~[topper-spigot-placeholder-leaderboard-2.5.0-shaded.jar:?]
        at me.hsgamer.topper.placeholderleaderboard.lib.core.bukkit.scheduler.Runner.lambda$runTaskTimer$0(Runner.java:53) ~[topper-spigot-placeholder-leaderboard-2.5.0-shaded.jar:?]
        at me.hsgamer.topper.placeholderleaderboard.lib.core.bukkit.scheduler.folia.FoliaScheduler.lambda$wrapRunnable$0(FoliaScheduler.java:42) ~[topper-spigot-placeholder-leaderboard-2.5.0-shaded.jar:?]
        at io.papermc.paper.threadedregions.scheduler.FoliaAsyncScheduler$AsyncScheduledTask.run(FoliaAsyncScheduler.java:217) ~[kaiiju-1.20.1.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.lang.Thread.run(Thread.java:1583) ~[?:?]

**Comment by HSGamer** [comment]
A fix will be soon. For now, go to the config and change the storage type to `sqlite`.
